package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class StudentController {

    // This means to get the bean called studentRepository which is auto-generated by Spring,
    // we will use it to handle the data
    @Autowired
    private StudentRepository studentRepository;

    // @RequestParam means it is a parameter from the GET or POST request
    // @ResponseBody means the returned String is the response, not a view name
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewStudent(@RequestParam String firstName,
                         @RequestParam String lastName,
                         @RequestParam String emailId){

        Student s = new Student();
        s.setFirstName(firstName);
        s.setLastName(lastName);
        s.setEmailId(emailId);

        Student savedStudent = studentRepository.save(s);
        return savedStudent.toString();
    }

    // This returns a JSON or XML with the students
    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Student> getAllStudents(){
        return studentRepository.findAll();
    }

}
